### ISSUE TITLE
Make sh_moveit_config more generic

### ISSUE THREAD

**Issue by YiShadow** [shadow-robot/sr-ros-interface#104]

**Comment by markpitchless** [comment]
Write some wiki pages.

**Comment by ugocupcic** [comment]
Look at this one to make it more generic.

https://github.com/shadow-robot/sr-ros-interface/pull/113/files

**Comment by guihomework** [comment]
Have a look at the updated https://github.com/shadow-robot/sr-contrib/tree/hydro-devel/sr_moveit_hand_config I generated and which works nice (tested in hydro) to plan motion with end-effectors at each finger-tip and with coupling capable IK, to avoid inter-finger collisions etc...

I also suggest to move this package out of the base driver (sr-ros-intercace) to maintain it independent from higher level planning. A good idea would be to upgrade sr_manipulation and include some metapackages like sr_manipulation_config sr_manipulation_tools sr_manipulation_gui and more.

**Comment by ugocupcic** [comment]
Removed
