### ISSUE TITLE
Create tactile receiver library in python

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#114]
Create a TactileReceiver that listens to the /tactile topic of the hand and stores the latest tactile message received for:
-biotacs
-pst

This object will be used by the hand Commander class (https://github.com/shadow-robot/sr-ros-interface/blob/hydro-devel/sr_hand/scripts/sr_hand/shadowhand_commander.py)
to offer the user an easy way to access the latest tactile data. e.g.

get_biotac_tactile_data()
get_pst_tactile_data()

**Comment by guihomework** [comment]
get_ubi_tactile_data ? ;-)  We are not using the hand commander, but I can probably extend it if you would like to cover all the sensor you support.
