### ISSUE TITLE
XFJ1 do not move in gazebo in F_ros_control

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/sr-ros-interface#139]
In F_ros_control, in the gazebo simulation, sending a command to sh_ffj0_position_controller/command only moves XFJ2, not XFJ1

Apparently the backward propagation of the force was somehow removed in sr_mechanism_model + sr_gazebo_plugin + ros_ethercat_model but might be necessary to correctly send a torque to both joints on the gazebo side although only one actuator controls the coupled joints.  
The only propagations available now are  :
- ActuatorPositionToJointPosition (needed to get generate position read from the actuator in the real hand) 
- JointEffortToActuatorEffort (needed to merge the joint efforts of a controller to the actuator in the real hand)

Missing is probably only :
- ActuatorEffortToJointEffort (needed to get the force to be sent to both gazebo joints in order to get both to move)

Not sure about  JointPositionToActuatorPosition

**Comment by shadowmanos** [comment]
Fixed in indigo-devel branch and tested with JointSliders GUI and Gazebo
