### ISSUE TITLE
IFMA lib onsite improvements

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-ros-interface#142]
- functions to send positions or torques to all joints
- send position in radians as expected instead of in degrees
- provide function to publish max_force_factor for each joint
- provide constructor of the ShadowHand class without arguments. Thus it will be easier to initialise in a thread without passing the command line arguments.
- having a single list with all joints is confusing as some are not actuated. The library should list the joints that report their state and the joints that are actuated.
- There is a bug where the joints zero are ignored for both joint state and actuation.
- bonus : read strain gauges values

**Comment by ugocupcic** [comment]
the strain gauges values are only published in the diagnostics for now I'm afraid. To get them we'd need to add a new publisher to the default controller I guess.

**Comment by shadowmanos** [comment]
Apparently Juan was happy with the effort in the joint state and didn't require strain gauges. The max_force thing was omitted. The other features are merged in both hydro-devel and indigo-devel
