### ISSUE TITLE
sim in gazebo broken

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-ros-interface#145]
simulation of our hand in gazebo is broken after getting latest ubuntu (14.04) packages for ROS (Indigo) on Friday 1 Aug 2014.
- After gazebo_hand.launch starts the hand appears momentarily and then disappears
- The effort is set for each joint correctly (output of controller)
- Positions of each joint remain the same as at the beginning of the simulation, e.g. they don't move after effort is applied.

Gazebo doesn't display errors apart from the usual like
Unable to get Material[LightGrey] for Geometry[shadow_model::ffmiddle::ffmiddle_visual. Object will appear white

**Comment by guihomework** [comment]
With the most recent trusty + ros install (from yesterday) and the most recent shadow indigo-devel sources + https://github.com/shadow-robot/sr-ros-interface/pull/147 there is no motion problem
