### ISSUE TITLE
test_sr_robot_lib is breaking pre-release tests

### ISSUE THREAD

**Issue by adolfo-rt** [shadow-robot/sr-ros-interface#152]
The test referred in the title is not passing, and is breaking the pre-release tests for `ros_control`, as it's one of the downstream dependencies.

Please refer to the [console output](http://jenkins.ros.org/job/prerelease-indigo-ros_control/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=prerelease/1/consoleText) of a recent run for details (amd64-trusty-indigo combination).

TIA

**Comment by shadowmanos** [comment]
That test is actually on a different repo and reported here shadow-robot/sr-ros-interface-ethercat#26. We couldn't find a solution for it when we tried so I will deactivate it to prevent such problems for other people.

**Comment by adolfo-rt** [comment]
Thanks for pointing out the relevant repo/issue. Closing then.
