### ISSUE TITLE
fix controllers and tranmissions for bimanual systems

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-ros-interface#167]
Currently it is assumed that the joint name has 4 letters and the fourth is the joint number. In a bimanual system FFJ0 for example will be rhFFJ0. So now the last letter of a variable length string will be the joint number.

**Comment by guihomework** [comment]
why not look for JX and use that as a pos for string replacement as it is done 
https://github.com/ubi-agni/sr-ros-interface/blob/ubi-groovy-devel/sr_mechanism_controllers/src/srh_mixed_position_velocity_controller.cpp
I this way what matters is the JX not the position in the string.

BTW, our current naming convention uses rh_FFJ0 to have a clear prefix separation. URDF xacros currently support any of the two anyway.

**Comment by shadowmanos** [comment]
@guihomework as discussed at Shadow today various prefixes may or may not be added but the last character will always represent the joint number. The code in the pull request is also a small change of the previously used. The underscore will not be a problem.
