### ISSUE TITLE
UR10 set up + configuration

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#211]
Install the UR10.
Set up arm:
- Network. Maybe use direct connection as we know it works well (no switch). Set fixed IP on arm control PC and host PC.
- specify as floor mounted
- set boundaries to avoid collisions with the floor

**Comment by toliver** [comment]
Use this branch of lma_kinematics_plugin for the arm kinematics. It takes into account the joint_limits parameter for the kinematics (the default version takes the URDF joint limits, which is inconvenient). 

https://github.com/shadow-robot/lma_kinematics_plugin/tree/F_ik_with_joint_limits

**Comment by ugocupcic** [comment]
Create a rosinstall in sr-build-tools package
