### ISSUE TITLE
error in execution of Cmake

### ISSUE THREAD

**Issue by sivammt** [shadow-robot/sr-ros-interface#266]
Hi, 

 When I try to execute catkin_make I get the following error. Kindly suggest me a solution.

![screenshot from 2015-04-28 12 17 12](https://cloud.githubusercontent.com/assets/10954679/7367558/8b5c0ca6-eda0-11e4-9a68-2c73b5817741.png)

**Comment by toliver** [comment]
Are you using the latest version of the indigo-devel branch?
It should work.

**Comment by sivammt** [comment]
That issue got solved but i got another while proceeding further. It shows 
/home/siva/catkin_ws/src/sr-ros interface/sr_mechanism_model/src/joint_0_transmission_for_muscle.cpp:75:13: error: ‘class ros_ethercat_model::JointState’ has no member named ‘effort_’

kindly help me with this.

![screenshot from 2015-04-28 15 19 53](https://cloud.githubusercontent.com/assets/10954679/7370430/5c90ae6c-edba-11e4-801f-cd7e34beeef6.png)

**Comment by toliver** [comment]
You need to install the ros_ethercat repository from source.

**Comment by sivammt** [comment]
Thanks a lot for the information.

On Tue, Apr 28, 2015 at 6:57 PM, toliver notifications@github.com wrote:

> You need to install the ros_ethercat repository from source.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shadow-robot/sr-ros-interface/issues/266#issuecomment-97136657
> .

## 

Sivakumar K
M.Tech Mechatronics
VIT University, India

**Comment by ugocupcic** [comment]
@sivammt is your problem solved now? Can I close this issue?

Cheers,

**Comment by sivammt** [comment]
Dear Ugo Cupcic,

   my problem is solved. Thanks a lot .:)

On Wed, Apr 29, 2015 at 5:41 AM, Ugo Cupcic notifications@github.com
wrote:

> @sivammt https://github.com/sivammt is your problem solved now? Can I
> close this issue?
> 
> Cheers,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shadow-robot/sr-ros-interface/issues/266#issuecomment-97296148
> .

## 

Sivakumar K
M.Tech Mechatronics
VIT University, India
