### ISSUE TITLE
UR10 Gazebo simulation problem

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#286]
For some reason the simulated UR10 arm doesn't move as it used to a few weeks ago.

**Comment by ugocupcic** [comment]
Fixed with latest indigo update.

**Comment by guihomework** [comment]
@ugocupcic does this mean system released update or from source compile of gazebo_ros/ gazebo-ros-control etc ?

**Comment by ugocupcic** [comment]
@guihomework system released update!
