### ISSUE TITLE
bad collision model for biotac tip

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/sr-ros-interface#309]
in srh_ur10 model, the fingertips can penetrate the upperarm up to the mounting adapter of the biotac ( green part penetrates, black part in collision)  

![biotac_badcollision_model](https://cloud.githubusercontent.com/assets/6583181/8024093/025ae4e8-0d28-11e5-9017-5e3f9aabfec4.png)

seems like the standard finger collision is used for biotac (not new version). should be fixed with a simplified biotac tip mesh or cylinder+sphere.

**Comment by beatrizleon** [comment]
@guihomework 

We have tested the model in rviz and in gazebo and could not reproduce the problem.

Here is the rviz screenshot showing that the collision happened in red:
![collisionrviz](https://cloud.githubusercontent.com/assets/12493239/8132838/615a2cea-111c-11e5-80ae-91c975656c84.png)

And here is a small video showing the collision happening in gazebo:
![gifrecord_2015-06-12_155543](https://cloud.githubusercontent.com/assets/12493239/8132856/74058704-111c-11e5-96b3-246aaf633884.gif)

**Comment by guihomework** [comment]
@beatrizleon thanks for checking, that was a quick closing, I did not even have time to look at it a second time. Will do that this week end, maybe updated link names fixed the collision now ?

I will probably comment here to confirm it is fixed or give more inputs on that issue.
