### ISSUE TITLE
Create commander example that shows how to generate a trajectory for the hand

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#337]
The example could show how to generate a trajectory that moves a joint in a sinusoid profile where `joint_pos = sin(t)` (obviously respecting max and min of the joint).

And then how to send the trajectory using the commander unsafe function.

**Comment by ugocupcic** [comment]
It can be found [here](https://github.com/shadow-robot/sr-ros-interface/blob/indigo-devel/sr_example/scripts/sr_example/commander/sinusoid_joint.py)
