### ISSUE TITLE
Add degree mode to the robot commander

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ros-interface#369]
As requested by @adelarosat, we need a "degree" mode for an easier to use robot commander. 

The easy way to do this would be to:
- add a `degrees=False` to the `...joint_value_target` functions in the robot_commander (for example [here](https://github.com/shadow-robot/sr-ros-interface/blob/indigo-devel/sr_robot_commander/src/sr_robot_commander/sr_robot_commander.py#L80) )
- check if `degrees is True` and convert the degrees to radians in the provided joint states (using math.degrees).
- use the new joint states (in radians) as before

Don't forget to update the doc and example!

**Comment by toliver** [comment]
I started migrating the demo some time ago. In this branch (https://github.com/shadow-robot/sr-ros-interface/compare/F_migrate_demo_to_robot_commander) you can also find some filtering for the hand to allow to hide J1 and J2 from the user, and show them as J0.

The filtering function we also converted to degrees.
