### ISSUE TITLE
Double check hand commander

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ros-interface#373]
Do we have all the functionalities we discussed:
- [x] store poses in db (from gui / current pose)
- [x] retrieve them and compose trajectory from multiple poses
- [x] cancel / override current command

And the live mode: use any ros callbacks, create new (partial) traj, send it to the controller (override)

**Comment by dg-shadow** [comment]
What does partial trajectory mean in this context?

**Comment by ugocupcic** [comment]
That's probably not working yet - it's based on @beatrizleon new controllers. If a trajectory for the whole hand is being run, sending a new trajectory for a sub-list of joints.

**Comment by dg-shadow** [comment]
We may have an interesting issue... @beatrizleon I think you realised this already... At the moment all trajectories are based on turning robot states into cartesian poses. How will that work with the hand?
