### ISSUE TITLE
Add instructions to update a source installation

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#399]
In previous versions of `INSTALL.md` we included instructions to update an existing source installation (based on wstool update, and installing any new source dependencies).
It seems that we still need that, don't we?

**Comment by ugocupcic** [comment]
Well in theory it would be rerunning the script, the problem is that I'd like to optimise it a bit better for updates.

**Comment by ugocupcic** [comment]
Simply add an alias to the bashrc that does `wstool for-each git pull`.
