### ISSUE TITLE
Some executables not compiled in release version

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#5]
The executable shadowhand_ethercat (in sr_hand) is not contained in the released .deb version of the stack. It is necesary to run the cyberglove (among other things).

This compilation depends on an environment variable (ETHERCAT=1) that is set in sr_config/bashrc/env_variables.bash.

The problem is that the debbuild process doesn't know anything about having to source sr_config/bashrc/env_variables.bash before building the shadow_robot stack.

**Comment by ugocupcic** [comment]
We should probably get rid of those defines for the compilation (except for the robot code) and compile everything by default. It will need some modifications for gazebo / virtual support as they are both contained in the same file for the time being.

**Comment by shadowmanos** [comment]
Fixed during other updates
