### ISSUE TITLE
Create a position-valve_cmd controller

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#50]

**Comment by toliver** [comment]
Created at 
sr_mechanism_controllers/src/srhMuscleJointPositionController.cpp

But the current algorithm to calculate the valve command for each of the 2 muscles is very basic, and useless as it is.

We need to improve this algorithm.

**Comment by markpitchless** [comment]
Updated with slightly better algo that uses PID loop to drive the valves over time. PID runs at 20Hz using a command accumulator of valve time to drive the values continuously at 1000Hz. Works ok with P only control, should be better with more tuning.
