### ISSUE TITLE
Test the muscle drivers bootloader

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#54]
Dan should program the boards with the bootloader, and provide the hex file with the latest firmware.

After the bootloading process check:
- That the boards behave correctly
- That they still have the correct ID in their EEPROM

**Comment by markpitchless** [comment]
If time decide on better dir for the muscle firm ware and set the default dir in the GUI plugin.

**Comment by markpitchless** [comment]
Didn't work. Amando ok to deliver with out this feature as it never gets used.
