### ISSUE TITLE
self test fails

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-ros-interface#69]
in branch R_hydro and in package sr_self_test
the sr_self_test.test fails with the message
ERROR: test max time allotted
and no other indications

**Comment by ugocupcic** [comment]
The self test takes a very long time to complete. Set the test max time to
a very big value (like 10min or something):

<test test-name="test_1_2" pkg="mypkg" type="test_1_2.py"
time-limit="10.0" args="--test1 --test2" />

ᐧ

On 18 December 2013 19:44, Manos Nikolaidis notifications@github.comwrote:

> in branch R_hydro and in package sr_self_test
> the sr_self_test.test fails with the message
> ERROR: test max time allotted
> and no other indications
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ros-interface/issues/69
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by shadowmanos** [comment]
closed by #150
