### ISSUE TITLE
Errors when linking tests in sr_mechanism_controllers

### ISSUE THREAD

**Issue by YiShadow** [shadow-robot/sr-ros-interface#72]
After updating ros hydro packages on Jan 21.

Branch: R_hydro

$ make tests
...
Linking CXX executable /home/liyi/sr_remap_ws/devel/lib/sr_mechanism_controllers/test_joint_pos_controller_with_fc
/opt/ros/hydro/lib/libpr2_mechanism_model.so: undefined reference to `KDL::Segment::~Segment()'
/opt/ros/hydro/lib/libpr2_mechanism_model.so: undefined reference to`KDL::Segment::Segment(KDL::Segment const&)'
...

**Comment by markpitchless** [comment]
You can work around this by putting latest pr2_mechanism_model (git@github.com:PR2/pr2_mechanism.git) in your src/.

These linking breakages on minor updates are getting annoying and time consuming :(

**Comment by toliver** [comment]
Very time consuming indeed.
I'm going to comment out the tests in `sr_mechanism_controllers` for our release.

We don't know when they are going to do another release of `pr2_mechanism_model`. When that happens we'll put the tests back in.

**Comment by ugocupcic** [comment]
Relay that info to pr2 people. Probably on github.
On Feb 12, 2014 6:39 PM, "toliver" notifications@github.com wrote:

> Very time consuming indeed.
> I'm going to comment out the tests in sr_mechanism_controllers for our
> release.
> 
> We don't know when they are going to do another release of
> pr2_mechanism_model. When that happens we'll put the tests back in.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ros-interface/issues/72#issuecomment-34894308
> .

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK
Registered Number 3308007 (England & Wales)

RoNeX - Building Robots with ROS Made Easy 

## http://www.shadowrobot.com/products/ronex/
