### ISSUE TITLE
Hand simulator namespaces

### ISSUE THREAD

**Issue by markpitchless** [shadow-robot/sr-ros-interface#75]
Update the gazebo sim to use the same namespaces as the real hand. ie /rh

**Comment by toliver** [comment]
We should try to get the solution that Guillaume has been working on to use the namespaced models on the sr_gazebo plugin. (See the email discussion about it).

I guess at some point (maybe end of February we'll get a pull request).

Ideally we want to be able to launch the simulation with or without the namespaces.

**Comment by markpitchless** [comment]
https://github.com/shadow-robot/sr-ros-interface/tree/F_gazebo_namespaces

**Comment by markpitchless** [comment]
How does the namespacing work when we have the arm in there, do we just push all the arm topics into /rh as well? That would probably be the easiest thing todo.
