### ISSUE TITLE
Update thoroughly our wiki.ros.org pages

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ros-interface#78]
We have had complaints from our sales team. Apparently some potential customers have almost given up on us after trying to run the simulated hand based on the wiki instructions.

So we should update our severely outdated public wiki pages in wiki.ros.org (at least for the currently supported ros versions).

http://wiki.ros.org/shadow_robot/
http://wiki.ros.org/shadow_robot/Tutorials

**Comment by toliver** [comment]
This task will deal with the tutorials only. Not the package documentation see #80 

So only 

http://wiki.ros.org/shadow_robot/Tutorials

**Comment by ugocupcic** [comment]
Using readthedoc instead
