### ISSUE TITLE
sr_gazebo

### ISSUE THREAD

**Issue by markpitchless** [shadow-robot/sr-ros-interface#95]
Create a sr_gazebo package.
- Move the gazebo launch files there from sr_hand. 
- Move gazebo config from sr_hand (hand_controllers.launch etc).
- Move sr_example touching_tactiles there and use it to write a quick test.
- Add a quick test that starts the sim and tests for the right topics are there. joint_states, controllers.
- Maybe a quick test that a joint will move.

**Comment by ugocupcic** [comment]
Would be too disruptive
